"""Add timestamp to userlikebot table

Revision ID: 14193890d9ad
Revises: e243a87758b8
Create Date: 2024-04-09 23:32:34.950474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14193890d9ad'
down_revision: Union[str, None] = 'e243a87758b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_likes_bots', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_likes_bots', 'created_at')
    # ### end Alembic commands ###
