"""Change group chat privacy default to not null

Revision ID: 3eef8f296165
Revises: 5a5ec3c3561b
Create Date: 2024-04-21 19:05:36.720359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eef8f296165'
down_revision: Union[str, None] = '5a5ec3c3561b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_chats', 'privacy',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'private'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_chats', 'privacy',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'private'::character varying"))
    # ### end Alembic commands ###
