"""add greeting

Revision ID: 56c53bfd3426
Revises: 
Create Date: 2024-02-20 15:44:29.500862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c53bfd3426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('greeting', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'bots', ['bot_id'])
    op.create_unique_constraint(None, 'chats', ['chat_id'])
    op.create_unique_constraint(None, 'messages', ['message_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.create_unique_constraint(None, 'voices', ['voice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voices', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_constraint(None, 'bots', type_='unique')
    op.drop_column('bots', 'greeting')
    # ### end Alembic commands ###
