"""Add privacy props to group chat

Revision ID: 5a5ec3c3561b
Revises: 8ddce7660b62
Create Date: 2024-04-21 19:03:20.274598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5ec3c3561b'
down_revision: Union[str, None] = '8ddce7660b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_chats', sa.Column('privacy', sa.String(), server_default='private', nullable=True))
    op.create_unique_constraint(None, 'group_chats', ['group_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_chats', type_='unique')
    op.drop_column('group_chats', 'privacy')
    # ### end Alembic commands ###
