"""add audio sample nullable

Revision ID: 79605f3391f7
Revises: 73358dc35c0b
Create Date: 2024-04-07 14:52:58.623741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79605f3391f7'
down_revision: Union[str, None] = '73358dc35c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voices', sa.Column('sample_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voices', 'sample_url')
    # ### end Alembic commands ###
