"""add block ips

Revision ID: 9e9a82982dc5
Revises: 06f78edd1f0a
Create Date: 2024-05-11 14:06:02.439843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9a82982dc5'
down_revision: Union[str, None] = '06f78edd1f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_ips',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ip'),
    sa.UniqueConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_ips')
    # ### end Alembic commands ###
