"""update bot props

Revision ID: cbe7c32c7153
Revises: 56c53bfd3426
Create Date: 2024-04-06 19:27:37.102498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe7c32c7153'
down_revision: Union[str, None] = '56c53bfd3426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('privacy', sa.String(), server_default='public', nullable=False))
    op.add_column('bots', sa.Column('gender', sa.String(), server_default='non-binary', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'gender')
    op.drop_column('bots', 'privacy')
    # ### end Alembic commands ###
