"""Update voice properties

Revision ID: e7c0b3c2dde0
Revises: 3eef8f296165
Create Date: 2024-04-22 10:07:13.572352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c0b3c2dde0'
down_revision: Union[str, None] = '3eef8f296165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voices', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('voices', sa.Column('language', sa.String(), server_default='en-US', nullable=True))
    op.add_column('voices', sa.Column('style', sa.String(), server_default='neutral', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voices', 'style')
    op.drop_column('voices', 'language')
    op.drop_column('voices', 'gender')
    # ### end Alembic commands ###
