from fastapi import FastAPI, Response, status, HTTPException, Depends, APIRouter
from sqlalchemy.orm import Session
from typing import List, Optional
import requests
from PIL import Image
import io
import os

from sqlalchemy import func
from app import models
from app.schemas import bot
from app.database import get_db
from app.auth import get_current_user
from app.config import configs, settings
from app.api.api_v1.dependency.utils import decode_base64
from app.api.api_v1.engines.storage.azure import azure_storage
from app.api.api_v1.engines.text.utils import UTILS, UtilsEngine
from app.api.api_v1.engines.image.base import ImageEngine

import time

router = APIRouter(
    prefix="/bot",
    tags=['Bot']
)

@router.get("/edit_bot/{bot_id}", 
            summary="Get bots by id only for user",
            description="Get bots by id only for user (for editing a bot)",
            response_model=bot.BotGet)
def get_bots_editting(
    bot_id: int,
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):  
    return db.query(models.Bot).filter(models.Bot.bot_id == bot_id).first()


@router.get("/created_bot", 
            summary="Get all bots created by user",
            description="Get all bots created by an user",
            response_model=List[bot.BotGet])
def get_bots(
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):  
    return db.query(models.Bot).filter(models.Bot.created_by == current_user).order_by(models.Bot.created_at.desc()).all()


@router.get("/liked_bot", 
            summary="Get all bots liked by user",
            description="Get all bots liked by an user",
            response_model=List[bot.BotGet])
def get_liked_bots(
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):  
    return db.query(models.Bot).join(models.user_likes_bots).filter(models.user_likes_bots.c.user_id == current_user).order_by(models.user_likes_bots.c.created_at.desc()).all()


@router.post("/", 
            summary="Create a new bot",
            description="Create a new bot",
            response_model=bot.BotGet, status_code=status.HTTP_201_CREATED)
def create_bot(
    bot_create: bot.BotCreate,
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):  
    db_bot = models.Bot(**bot_create.dict())
    db.add(db_bot)
    db.commit()
    db.refresh(db_bot)

    bot_id = db_bot.bot_id

    image_path = f"app/api/api_v1/dependency/temp_img_{bot_id}.webp"
    image_url = bot_create.profile_picture
    if image_url.startswith('https'):
        # when image is generated by AI
        generated_image = requests.get(image_url).content
        image = Image.open(io.BytesIO(generated_image))
        image.save(image_path, 'WEBP')
    else:
        # when image is uploaded by user
        image_data = decode_base64(image_url)
        image = Image.open(io.BytesIO(image_data))
        image.save(image_path, 'WEBP')

    image_upload = f"{bot_id}.webp"

    azure_storage.upload_blob(image_path, "ttl-images", image_upload)

    db_bot.profile_picture = f"{settings.azure_db_endpoint}/ttl-images/{image_upload}"
    db.commit()
    db.refresh(db_bot)

    os.remove(image_path)

    return db_bot


@router.post("/create_bot/generate", 
            summary="Generate greeting and short description",
            description="Generate greeting and short description when creating a new bot",
            status_code=status.HTTP_200_OK
            )
def generate_bot(
    bot_create: bot.BotGenerate,
    current_user: str = Depends(get_current_user)
):
    engine = UtilsEngine(
        character_name=bot_create.bot_name,
        character_description=bot_create.description,
        util=UTILS[0]
    )

    greeting, description = engine.process_response_util_0(engine.get_response())

    return {
        "greeting": greeting,
        "short_description": description
    }


@router.post("/create_bot/optimize_description", 
            summary="Optimize bot description from existing description",
            description="Optimize bot description from existing description when creating a new bot",
            status_code=status.HTTP_200_OK
            )
def optimize_bot(
    bot_optimize: bot.BotGenerate,
    current_user: str = Depends(get_current_user)
):
    engine = UtilsEngine(
        character_name=bot_optimize.bot_name,
        character_description=bot_optimize.description,
        util=UTILS[1]
    )

    optimized_description = engine.get_response()

    return optimized_description


@router.post("/create_bot/generate_img_prompt", 
            summary="Generate image promptfor character",
            description="Generate image prompt for character when creating a new bot",
            status_code=status.HTTP_200_OK
            )
def generate_img_prompt(
    bot_optimize: bot.BotGenerate,
    current_user: str = Depends(get_current_user)
):
    engine = UtilsEngine(
        character_name=bot_optimize.bot_name,
        character_description=bot_optimize.description,
        util=UTILS[2]
    )

    image_prompt = engine.get_response()

    return image_prompt


@router.post("/create_bot/optimize_img_prompt", 
            summary="Optimize image prompt for character",
            description="Optimize image prompt for character when creating a new bot",
            status_code=status.HTTP_200_OK
            )
def optimize_img_prompt(
    image_prompt: bot.ImagePrompt,
    current_user: str = Depends(get_current_user)
):
    engine = UtilsEngine(
        image_prompt=image_prompt.image_prompt,
        util=UTILS[3]
    )

    optimized_prompt = engine.get_response()

    return optimized_prompt


@router.post("/create_bot/generate_image", 
            summary="Generate image from a prompt for character",
            description="Generate image from a prompt for character when creating a new bot",
            status_code=status.HTTP_200_OK
            )
def generate_avatar(
    image_prompt: bot.ImagePrompt,
    current_user: str = Depends(get_current_user)
):  
    engine = ImageEngine(
        image_prompt=image_prompt.image_prompt,
        provider=configs.IMAGE_PROVIDER_1
    )

    image_url = engine.get_image_response()

    return image_url


@router.patch("/{id}", 
            summary="Update bot information",
            description="Update bot information by bot id",
            response_model=bot.BotGet,
            status_code=status.HTTP_200_OK)
def update_bot(
    id: int,
    bot_update: bot.BotUpdate,
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):
    db_bot = db.query(models.Bot).filter(models.Bot.bot_id == id).first()

    if not db_bot:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Bot not found")

    for var, value in bot_update.dict().items():
        if value is not None and var != "profile_picture":
            setattr(db_bot, var, value)

    if bot_update.profile_picture:
        image_path = f"app/api/api_v1/dependency/temp_img_{id}.webp"
        image_url = bot_update.profile_picture
        if image_url.startswith('https'):
            # when image is generated by AI
            generated_image = requests.get(image_url).content
            image = Image.open(io.BytesIO(generated_image))
            image.save(image_path, 'WEBP')
        else:
            # when image is uploaded by user
            image_data = decode_base64(image_url)
            image = Image.open(io.BytesIO(image_data))
            image.save(image_path, 'WEBP')

        image_upload = f"{id}.webp"

        azure_storage.delete_blob("ttl-images", image_upload)

        azure_storage.upload_blob(image_path, "ttl-images", image_upload)

        db_bot.profile_picture = f"{settings.azure_db_endpoint}/ttl-images/{image_upload}"

        os.remove(image_path)

    db.commit()
    db.refresh(db_bot)
    return db_bot


@router.post("/like/{bot_id}", 
            summary="User likes a bot",
            description="User likes a bot by bot id",
            status_code=status.HTTP_200_OK)
def likes_bot(
    bot_id: int,
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):
    
    bot_to_like = db.query(models.Bot).filter(models.Bot.bot_id == bot_id).first()
    
    if not bot_to_like:
        raise HTTPException(status_code=404, detail="Bot not found")

    existing_like = db.query(models.user_likes_bots).filter_by(
        user_id=current_user,
        bot_id=bot_id
    ).first()

    if existing_like:
        return Response(status_code=status.HTTP_200_OK)

    db.execute(
        models.user_likes_bots.insert().values(
            user_id=current_user,
            bot_id=bot_id
        )
    )
    db.commit()

    return Response(status_code=status.HTTP_200_OK)


@router.delete("/unlike/{bot_id}", 
               summary="User unlikes a bot",
               description="User unlikes a bot by bot id",
               status_code=status.HTTP_200_OK)
def unlike_bot(
    bot_id: int,
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):
    
    bot_to_unlike = db.query(models.Bot).filter(models.Bot.bot_id == bot_id).first()
    
    if not bot_to_unlike:
        raise HTTPException(status_code=404, detail="Bot not found")

    existing_like = db.query(models.user_likes_bots).filter_by(
        user_id=current_user,
        bot_id=bot_id
    ).first()

    if not existing_like:
        raise HTTPException(status_code=404, detail="Like not found")

    db.execute(
        models.user_likes_bots.delete().where(
            models.user_likes_bots.c.user_id == current_user,
            models.user_likes_bots.c.bot_id == bot_id
        )
    )
    db.commit()

    return Response(status_code=status.HTTP_200_OK)


@router.delete("/{id}", 
            summary="Delete bot by id",
            description="Delete bot by bot id",
            status_code=status.HTTP_204_NO_CONTENT)
def delete_bot(
    id: int,
    db: Session = Depends(get_db), 
    current_user: str = Depends(get_current_user)
):
    db_bot = db.query(models.Bot).filter(models.Bot.bot_id == id).first()

    if db_bot.created_by != current_user:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="User not authorized to delete bot")

    if not db_bot:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Bot not found")

    azure_storage.delete_blob("ttl-images", f'{db_bot.bot_id}.webp')

    db.delete(db_bot)
    db.commit()

    return Response(status_code=status.HTTP_204_NO_CONTENT)